### ISSUE TITLE
能否添加对 ADS PDK的支持？

### ISSUE THREAD

**Issue by artwe** [YongshengGuo/GDSImportWizard#1]
适用于ADS的PDK没有iRCX文件，能否支持ADS PDK的衬底文件格式？

**Comment by YongshengGuo** [comment]
Hi artwe, 我这边没有ADS PDK文件进行测试，如果文件是明文的，你可以使用工具提供的CSV Tech模板进行转换，或者写一个中间脚本。 需要帮助可以通过yongsheng.guo@ansys.com联系我。
